### PR TITLE
Do not fail if Federation app is not enabled

### LINKED ISSUE #117: Testing app requires federation app to be enabled
It looks like PR #101 added features to the testing app that require the `federation` app to be enabled.

- check if this is true (disable `federation` and then try to run some ordinary acceptance tests that should run without federation)
- think of a way to adjust the testing app so that it can do its job, and still work cleanly (maybe with a little less functionality) when the `federation` app is disabled
- think if there are other core apps that the testing app depends on, and what we could do about that
- document whatever dependencies are unavoidable

### PR DESCRIPTION
**Pull request by skshetry**
## Description

Currently, if federation app gets disabled, the classes cannot be imported into the namespace,
and the server starts failing (but gives 200 response). This adds a handler that will return a better response if the federation app is disabled.
 
Fixes #117 

## Checklist:

- [ ] Latest changes are published according to [instructions in README.md](https://github.com/owncloud/testing#publish-latest-version-as-github-release)

### CODE REVIEW

File: appinfo/routes.php [hunk 1]
```diff
@@ -305,40 +305,45 @@
 	API::ADMIN_AUTH
 );
 
-$trustedServers = new TrustedServersHandler(\OC::$server->getRequest());
 
+$trustedServers = new TrustedServersHandler(\OC::$server->getRequest());
```
Comment (phil-davis) [inline appinfo/routes.php]: The whitespace moved

**Comment by phil-davis** [comment]
code style fails

File: lib/TrustedServersHandler.php [hunk 2]
```diff
@@ -21,10 +21,10 @@
 
 namespace OCA\Testing;
 
+use OCP\API;
 use OCA\Federation\TrustedServers;
```
Comment (skshetry) [inline lib/TrustedServersHandler.php]:
```suggestion
```
